[tool.poetry]
name = "homework-12-2-2"
version = "0.1.0"
description = ""
authors = ["Nikita-Musk <nik52119q@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
